# Inheritance
- a class can inherit from other class
- it improve code reuse
- construcor ,attribute and method are inheritance to child class
- parent class has no access to child class
- child class methods overrides the parent class methods
 - this is called method overriding 
- super() method is used to invoke parent class method and constructor

## Single inheritance

In [5]:
class Person:
    def __init__(self,name):
        self.name=name
    def show(self):
        print(self.name+"is a python teacher")
class Professor(Person):
    def display(self):
        print("This is ",self.name)

In [6]:
per=Professor("Guido Rossum")

In [3]:
per.name

'Guido Rossum'

In [4]:
per.show()

Guido Rossumis a python teacher


## Multilevel inheritance

In [12]:
class Human:
    def __init__(self,name):
        self.name=name
    def show(self):
        print(self.name)
class Person(Human):
        pass
class Professor1(Person):
        pass


In [13]:
p=Professor1("abc")

In [14]:
p.name

'abc'

## Multiple inheritance

In [15]:
class Person:
    def __init__(self,name):
        self.name=name
    def show(self):
        print(self.name)
class Teacher:
        def credit(self):
            print("he teaches python")
class PythonProgrammer(Person,Teacher):
        pass

In [16]:
p1=PythonProgrammer("hi")

In [18]:
print(p1.credit())

he teaches python
None
hi


In [19]:
p1.name

'hi'

## Hiearchical inheritance

In [27]:
class Human:
    def __init__(self,name):
        self.name=name
    def show(self):
        print(self.name+" is a professor")
class pythonprogrammer(Human):
    pass
class javaprogrammer(Human):
    pass

In [22]:
p=pythonprogrammer("xyz")

In [23]:
p.show()

xyzis a professor


In [28]:
j=javaprogrammer("pqr")

In [29]:
j.show()

pqr is a professor


## Constructor Overriding

In [30]:
class Father:
    def __init__(self):
        self.money=10000
        print("Father class Constr")
    def show(self):
        print("Father class method")
class Son(Father):
    def __init__(self):
        self.money=500
        self.car="BMW"
        print("son class Constr")
    def display(self):
        print("son class method")


In [31]:
s=Son()

son class Constr


In [32]:
s.money

500

In [33]:
f=Father()

Father class Constr


In [34]:
f.money

10000

## `super() method`
- if we write constructor in both parent and child class,the parent class constrc is not available in child class
- `super()` method is used to call parent class from the child class

In [36]:
class Phone:
    def __init__(self,price,brand,camera):
        print("inside phone class")
        self.price=price
        self.brand=brand
        self.camera=camera
    def buy(self):
        print("Buying phone")
class SmartPhone(Phone):
    def buy(self):
        print("Buying a smartphone")
        super().buy()

In [38]:
s=SmartPhone(20000,'iphone',13)

inside phone class


### another example

In [41]:
class Father:
    def __init__(self):
        self.money=10000
        print("Father class constructor")
    def show(self):
        print("Father class method")
class Son(Father):
    def __init__(self):
        super().__init__()
        print("son calss const")
    def display(self):
        print("son class method ")

In [42]:
s=Son()

Father class constructor
son calss const


In [43]:
s.money

10000

# Polymorphism
- condition of occurence in diffrent forms
- at operator level
- at function level
- at method level

In [45]:
class Car:
    def start(self):
        print("Engine started")
    def move(self):
        print("car is running")
    def stop(self):
        print("brake applied")
class Clock:
    def move(self):
        print("tic tic tic")
    def stop(self):
        print("clock stopped")
class Person:
    def move(self):
        print("person is moving")
    def stop(self):
        print("person stoped")

In [47]:
c= Car()
c1=Clock()
p=Person()

In [48]:
def dosomething(x):
    x.move()
    x.stop()

In [50]:
dosomething(c)

car is running
brake applied


In [51]:
dosomething(c1)

tic tic tic
clock stopped


In [52]:
dosomething(p)

person is moving
person stoped


## operator overloading

In [53]:
print(2+3)
print("2"+"3")

5
23


## Function overloading

In [56]:
print(len("python"))
print(len(["ver1","ver2","ver3"]))
print(len({"Creator":"aa","nationality":"dutch"}))

6
3
2


## Abstract class
- a class derived from BAC class which belong to abc module is called abstract class in python
- ABC class is known as meta class which means class that defines behaviour of other classes.
- Abstarct class can have concreate and abstract methods
- Abstract class needs to be extended and its methods implemented 
- one cannot create object of an abstract class

In [67]:
from abc import ABC,abstractmethod
class DefenceForce(ABC):
    def __init__(self):
        self.id=101
    @abstractmethod
    def area(self):
        pass
    def gun(self):
        print("the gun is ak47")

In [73]:
class Army(DefenceForce):
    def area(self):
        print("area is land",self.id)

In [74]:
a=Army()

In [75]:
a.area()

area is land 101


In [77]:
a.gun()

the gun is ak47


In [78]:
class Navy(DefenceForce):
    def area(self):
        print("area is sea",self.id)

In [83]:
n=Navy()

In [80]:
n.area()

area is sea 101


In [81]:
n.gun()

the gun is ak47


In [82]:
n.id

101

## Create an abstract class Shape with abstract method `calculate_area`. Create two class Rectangle  and  Circle inheriting from shape. Create two object of rectangle and circle and find the area of these objects

In [108]:
from abc import ABC,abstractmethod
import math
class Shape(ABC):
    @abstractmethod
    def calculate_area():
        pass
    

In [113]:
class Rectangle(Shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
    def calculate_area(self):
        print(self.l*self.b)

In [119]:
class Circle(Shape):
    def __init__(self,r):
        self.r=r
    def calculate_area(self):
        print(math.pi*(self.r**2))

In [115]:
r=Rectangle(10,20)
r.calculate_area()

200


In [120]:
c=Circle(10)
c.calculate_area()

314.1592653589793


### pb 632
Implement the following hierarchy . The Book function has name, n (number of authors), authors (list of authors), 
publisher, ISBN, and year as its data members and the derived class has course as its data member. The derived class 
method overrides (extends) the methods of the base
class. 

In [121]:
class Book:
    def __init__(self,name,n,authors,publisher,ISBN,year):
        self.name=name
        self.n=n
        self.authors=authors
        self.publisher=publisher
        self.ISBN=ISBN
        self.year=year
    def display(self):
        print(self.name)
        print(self.n)
        print(self.authors)
        print(self.publisher)
        print(self.ISBN)
        print(self.year)
class derivedBook(Book):
        def __init__(self,name,n,authors,publisher,ISBN,year,course):
            super().__init__()
            self.course=course
        def display(self):
            #super().display
            print(self.name)
            print(self.n)
            print(self.authors)
            print(self.publisher)
            print(self.ISBN)
            print(self.year)

In [122]:
b=Book('name1',12,['aut1','aut2'],'pub1',2776,2006)

In [123]:
b.display()

name1
12
['aut1', 'aut2']
pub1
2776
2006


## Method resolution order in python
- It defines an order in which the class is searched  in case of multiple inheritance
- It is based on C3 Linearlization Algorith (>=python2.3)

## C3 linearization algorithm
- For a list of classes - C1C2C3..Cn
  - the C1 is the head of class and the rest is tail
- C3 linearization algorith is defined as MRO of sum of any class C and linear of parent and the list of parents

    L(C(B1,B2...BN)) = C + merge (L(B1),L(B2)...BN))
- Here B1 to BN ae the parent classes of C
1. Take the head of first list L(B1) from left to right
2. If the head of selected class is not in the tail of the list add it to the linear and remove it from the list 
3. Repeat the process untill the classes are removed or it is impossible to find good head

In [1]:
class F:
    pass
class E:
    pass
class D:
    pass
class C(D,F):
    pass
class B(D,E):
    pass
class A(B,C):
    pass

In [2]:
A.mro()

[__main__.A,
 __main__.B,
 __main__.C,
 __main__.D,
 __main__.E,
 __main__.F,
 object]

### First step
- MRO OF D,E,F,O
- L(D) = DO
- L(E) = EO
- L(F) = FO
- L(O) = O


### Second step
- L(C)=C+MERGE(L(D),L(F),DF)
-     =C+ MERGE(DO,FO,DF)
-     =C+D+MERGE(O,OF,F)
-     =C+D+F+O
-     =CDFO

### Third Step
- L(B) = B + merge(L(D),L(E),DE)
-     = B + MERGE(DO, EO, DE)
-     = B + D + MERGE(O, EO, E)
-     = B + D + E + O
-     = BDEO


## Four Step
- L(A) = A + MERGE(L(B),L(C),BC)
-     = A + MERGE(BDEO,CDFO,BC)
-     = A + B + MERGE(DEO , CDFO , C)
-     = A + B + C+ MERGE(DEO,DFO)
-      = A + B + C+D MERGE(EO,FO)
-      = A + B + C+ D + E +F + O
    

In [3]:
class A:  #AO
    pass
class B:      #BO
    pass
class C:      #CO
    pass
class D:     #DO
    pass
class E:     #EO
    pass
class K1(C,A,B):      # K1CABO
    pass
class K3(A,D):      #K3AD
    pass
class K2(B,D,E):      #K2BDE
    pass
class Z( K1,K3,K2):      #Z + MERGE(K1CABO,K3AD,K2BDE+ZK1K3K2)
                        # ZK1CK3AK2BDEO
                        # ZK1CK3AK2BDEO
            
    pass

In [4]:
Z.mro()

[__main__.Z,
 __main__.K1,
 __main__.C,
 __main__.K3,
 __main__.A,
 __main__.K2,
 __main__.B,
 __main__.D,
 __main__.E,
 object]

### INCONSISTENT MRO 

In [5]:
class A:
    pass
class B:
    pass
class C(A,B):
    pass
class D(B,A):
    pass
class X(C,D):
    pass

TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B

### OPERATOR OVERLOADING
__add__= +
__sub__= +
__mul__= +
__truediv__= +

In [14]:
class Fraction:
    def __init__(self,x,y):
        self.num=x
        self.den=y
    def __add__(self,other):
        new_num=self.num*other.den + other.num*self.den
        new_den=self.den * other.den
        return f"{new_num}/{new_den}"
    def __sub__(self,other):
        new_num=self.num*other.den - other.num*self.den
        new_den=self.den * other.den
        return f"{new_num}/{new_den}"
    def __mul__(self,other):
        new_num=self.num*other.num
        new_den=self.den * other.den
        return f"{new_num}/{new_den}"
    def __truediv__(self,other):
        new_num=self.num*other.den
        new_den=self.den * other.num
        return f"{new_num}/{new_den}"

In [9]:
Fraction1=1/3
Fraction2=2/5

In [17]:
f=Fraction(1,3)
g=Fraction(2,3)

In [18]:
f+g

'9/9'

In [19]:
f-g

'-3/9'

## wap to create a class data with the data member value create two objs of the class to demonstrate comparion operators

In [37]:
class Data:
    def __init__(self,x):
        self.x=x
    def __eq__(self,other):
        return self.x==other.x
    def __lt__(self,other):
        return self.x<other.x
    def __gt__(self,other):
        return self.x>other.x

In [47]:
a=Data(4)
b=Data(10)

In [48]:
a<b

True

In [45]:
a>b

True

In [46]:
a==b

False

# NUMPY

In [1]:
import numpy as np

In [2]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000002D798556D90>, toplevel='numpy')>

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [6]:
np.array??

In [7]:
arr=np.array([1,2,3,4,5])

In [10]:
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.19.2


## 2D Array

In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


## 3D array

In [16]:
import numpy as np

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype=float)


## dtype

In [17]:
#--------------meet

## Array Attribute

### ndim

In [33]:
a1=np.array([0,1,2,3,4,5,6,7,8,9])
a = np.array([0,1,2,3,4,5,6,7,8,9]) 
b = np.array([[1,2,3],[4,5,6]])  
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) 

In [27]:
a2=np.arange(10)

In [29]:
print(a1)
print(a2)
print(a1.ndim)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
1


## shape

In [30]:
a1.shape

(10,)

## size

In [31]:
a1.size

10

In [36]:
a1.itemsize
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
4
4


In [35]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## Reshape

In [42]:
a1=np.arange(12).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Scalar operation

In [44]:
print(a1+2)
print(a1) # it is view only

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
print(a1*2)
print(a1/2)
print(a1//2)
print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### np.sort - view only
- Return a sorted copy of an array

In [46]:
a= np.array([58,67,12,45,53,89,93])

In [49]:
print(np.sort(a))
print(a)

[12 45 53 58 67 89 93]
[58 67 12 45 53 89 93]


In [50]:
np.sort(a)[::-1]

array([93, 89, 67, 58, 53, 45, 12])

### np.concatenate
- it concatinate a sequence of arrays along the existing axis

In [57]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [58]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.nditer

In [51]:
a=np.array([58,67,12,45,53,89,93])

In [52]:
for i in a:
    print(i)

58
67
12
45
53
89
93


In [53]:
for i in np.nditer(a):
    print(i,end=" ")

58 67 12 45 53 89 93 